# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.11.0
  hooks:
  - id: gitleaks-docker
    name: Detect hardcoded secrets
    description: Detect hardcoded secrets using Gitleaks
    entry: zricethezav/gitleaks protect --verbose --redact --staged
    language: docker_image
