
apiVersion: v1
kind: Namespace
metadata:
  name: scheduling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: scheduling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: web-server
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: main
      volumes:
      - configMap:
          name: main-page
          items:
          - key: index.html
            path: index.html
        name: main
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: main-page
  namespace: scheduling
data:
  index.html: "<html>\n<title>Online Clock</title>\n<head>\n<script type="text/javascript">\nfunction startTime()\n{\nvar today=new Date();\nvar h=today.getHours();\nvar m=today.getMinutes();\nvar s=today.getSeconds();\n// add a zero in front of numbers<10\nm=checkTime(m);\ns=checkTime(s);\ndocument.getElementById('txt').innerHTML=h+":"+m+":"+s;\nt=setTimeout('startTime()',500);\n}\nfunction checkTime(i)\n{\nif (i<10)\n{\ni="0" + i;\n}\nreturn i;\n}\n</script>\n</head>\n<body onload="startTime()">\n<font style="font-size:30px">\nThe time is\n<div id="txt"></div>\n</body>\n<footer>\n<font style="color:blue">\nYou should get a watch\n</footer>\n</html>"
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: scheduling
spec:
  selector:
    matchLabels:
      app: webserver
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pressure
  namespace: scheduling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
      - name: load-test
        image: pstauffer/curl
        command: ["/bin/sh"]
        args: ["-c","while true; do curl webserver.scheduling.svc.cluster.local; sleep 1; done"]
        resources:
          requests:
            cpu: 50m
            memory: 50mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: special
  namespace: scheduling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: special
  template:
    metadata:
      labels:
        app: special
    spec:
      containers:
      - name: super-special-workload
        image: nginx:latest
