apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: v1
    spec:
      containers:
      - name: demo-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index
        configMap:
          name: demo
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  index.html: |
    <html>
    <body style="background-color:$BCOLOR">
    <h1 style="color:$LCOLOR">
    Hi $NAME,
    The variables you set should have changed the background color and the color of this text
    </h1>
    <h2>Set environment variables BCOLOR, LCOLOR, and NAME to change this page.</h2>
    </body>
    </html>
